### ISSUE TITLE
Вероятно неправильная форма леммы для глаголов

### ISSUE THREAD

**Issue by DenisNP** [lepeap/DeepMorphy#1]
Привет, отличный проект, давно ждал что-то вроде pymorphy2 для шарпа!

Для глаголов лемма это инфинитив несовершенного вида. Библиотека возвращает мужской род, например:

```csharp
var morph = new MorphAnalyzer( true);
var results = morph.Parse(new[] {"раскладывала", "обучает", "пересказывают"});
foreach (var res in results)
{
    Console.WriteLine(res.ToString());
}
```

> раскладывала : Lemma: **раскладываю** Tags: гл,жен,ед,прош
> обучает : Lemma: **обучаю** Tags: гл,ед,3л,наст
> пересказывают : Lemma: **пересказываю** Tags: гл,мн,3л,наст

**Comment by lepeap** [comment]
Привет. Спасибо!
Да с глаголами есть сейчас такая проблема. Я поздно заметил, что в словаре opencorporа для глаголов в качестве леммы задается не инфинитив (пример [обучаю](http://opencorpora.org/dict.php?act=edit&id=200849)). Поэтому сеть обучалась для глаголов выдавать 1-е лицо единственное число мужской род. 
В следующей версии постараюсь вытащить инфинитив и переобучиться.

**Comment by lepeap** [comment]
Поправил. С версии 1.2.1 выдаются корретные формы.
```csharp
var morph = new MorphAnalyzer( true);
var results = morph.Parse(new[] {"раскладывала", "обучает", "пересказывают"});
foreach (var res in results)
{
    Console.WriteLine(res.ToString());
}
```
> раскладывала : Lemma: раскладывать Tags: гл,жен,ед,прош
> обучает : Lemma: обучать Tags: гл,ед,3л,наст
> пересказывают : Lemma: пересказывать Tags: гл,мн,3л,наст
