### ISSUE TITLE
Лемма для слова "порту" => "порту", хотя правильная "порт"

### ISSUE THREAD

**Issue by mdima77** [lepeap/DeepMorphy#5]
Собственно сабж.

**Comment by lepeap** [comment]
Здравствуйте.
Тут ошибки нет, дело в омонимах. Есть несколько вариантов [разбора](http://opencorpora.org/dict.php?search_form=%D0%BF%D0%BE%D1%80%D1%82%D1%83&act=lemmata). 
В возможных вариантах от DeepMorphy указываются все случаи, причем равновероятно.
![image](https://user-images.githubusercontent.com/18688011/89558393-d5732b00-d81c-11ea-9ebf-c2d9da373487.png)
