### ISSUE TITLE
DeepMorphy для .Net Core

### ISSUE THREAD

**Issue by srabieb** [lepeap/DeepMorphy#6]
Здравствуйте!
Будет ли версия для .Net Core?

Библиотека не работает на .net core проекте.
Или есть какие то решения?

**Comment by lepeap** [comment]
Здравствуйте! 
Все должно работать на .Net Core.
В решении есть проект [ExampleConsole](https://github.com/lepeap/DeepMorphy/tree/master/src/cs/ExampleConsole) на core 2.2, все работает.  Сам пакет в других проектах у меня работает на 2.2, вроде без проблем...Сейчас попробовал, вроде на 3.1 тоже все нормально.

**Comment by lepeap** [comment]
Тут ошибка не из-за .net core, а из-за загрузки c++ tensorflow библиотеки.
Подобная ошибка была встречалась в этом тикете: https://github.com/lepeap/DeepMorphy/issues/4#issuecomment-634201118
Правда там в итоге человек так и не отписался, помогло ли ему предложенное решение.

**Comment by srabieb** [comment]
> Тут ошибка не из-за .net core, а из-за загрузки c++ tensorflow библиотеки.
> Подобная ошибка была встречалась в этом тикете: [#4 (comment)](https://github.com/lepeap/DeepMorphy/issues/4#issuecomment-634201118)
> Правда там в итоге человек так и не отписался, помогло ли ему предложенное решение.

Да вроде все уже установлено. не знаете чего не хваетает?
![image](https://user-images.githubusercontent.com/26784284/95899055-c9be5a80-0db1-11eb-99e0-a35963bcb664.png)

**Comment by lepeap** [comment]
Сам на линуксе и маке сижу в данный момент, возможности протестить на винде нет(
А проект в студии собирается? Если в режиме Any CPU, то можно попробовать явно выставить x64
